# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: MU Design Engineering Blog
email: masamichi1023@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  Hello, my name is Masamichi and I am a design engineer.
  I am an enthusiast of app development and design, and love being creative.
  This site is Design Engineering Blog written by me.

baseurl: "/blog" # the subpath of your site, e.g. /blog
url: "http://uetamasamichi.com" # the base hostname & protocol for your site
twitter_username: micchyboy
github_username:  micchyboy1023
author: Masamichi Ueta

# Build settings
markdown: kramdown

gems:
  - jekyll-seo-tag
